Updated initscript

diff --git a/debian/cherokee.init b/debian/cherokee.init
--- a/debian/cherokee.init
+++ b/debian/cherokee.init
@@ -25,16 +25,27 @@ set -e
 
 test -x $DAEMON || exit 0
 
+report_success() {
+    if [ $? = 0 ]; then
+	echo $NAME
+    else
+	echo "$NAME - Failed."
+	false
+    fi
+}
+
 case "$1" in
   start)	
-	printf "Starting web server: %s\t" "$NAME"
+	echo -n "Starting web server ($NAME): "
 	start-stop-daemon --start --oknodo --pidfile $PIDFILE --exec $DAEMON -b
+	report_success
 	;;
 
   stop)
-	printf "Stopping web server: %s\t" "$NAME"
+	echo -n "Stopping web server ($NAME): "
 	start-stop-daemon --stop --oknodo --pidfile $PIDFILE --exec $DAEMON
 	rm -f $PIDFILE
+	report_success
 	;;
 
   restart)
@@ -44,7 +55,7 @@ case "$1" in
 	;;
 
   reload|force-reload)
-	printf "Reloading web server: %s\t" "$NAME"
+	echo -n "Reloading web server: "
 	if [ -f $PIDFILE ]
 	    then
 	    PID=$(cat $PIDFILE)
@@ -59,6 +70,7 @@ case "$1" in
 	    echo "No PID file present for $NAME - Cannot reload"
 	    exit 1
 	fi
+	report_success
 	;;
 
   status)
@@ -71,19 +83,19 @@ case "$1" in
 	if [ -e $PIDFILE ] ; then
 	    PROCNAME=$(ps -p $(cat $PIDFILE) -o comm=)
 	    if [ "x$PROCNAME" = "x" ]; then
-		printf "Not running, but PID file present \t"
+		echo "Not running, but PID file present"
 	    else
 		if [ "$PROCNAME" = "$NAME" ]; then
-		    printf "Running\t"
+		    echo "Running"
 		else
-		    printf "PID file points to process '%s', not '%s'\t" "$PROCNAME" "$NAME"
+		    echo "PID file points to process '$PROCNAME', not '$NAME'"
 		fi
 	    fi
 	else
 	    if PID=$(pidofproc $DAEMON); then
-		printf "Running (PID %s), but PIDFILE not present\t" "$PID"
+		echo "Running (PID $PID), but PIDFILE not present"
 	    else
-		printf "Not running\t"
+		echo "Not running\t"
 	    fi
 	fi
 	;;
@@ -94,13 +106,5 @@ case "$1" in
 	exit 1
 	;;
 esac
-
-if [ $? = 0 ]; then
-        echo .
-        exit 0
-else
-        echo failed
-        exit 1
-fi
 
 exit 0
