Imported Upstream version 0.6.1

diff --git a/cherokee/cherokee-panic b/cherokee/cherokee-panic
--- a/cherokee/cherokee-panic
+++ b/cherokee/cherokee-panic
@@ -4,7 +4,11 @@
 # Possible actions are:
 #   mail - mail the error. You need a working MTA in the system.
 #   cat  - just print it
-action=mail
+if [ -x /usr/sbin/sendmail ]; then
+   action=mail
+else
+   action=cat
+fi
 
 # Redirect all output to our mail command
 (
@@ -24,12 +28,19 @@ action=mail
 	    action="$2"
 	fi
 
+	# Mail header
+	if [ x$action = xmail ]; then
+	    echo "To: root"
+	    echo "Subject: Segfault in Cherokee"
+	    echo
+	fi
+
+	# Find out what binary we're debugging
 	if [ ! -d "/proc/$pid" ]; then
 		echo "$0: No such process: $pid"
 		exit 1
 	fi
 
-	# Find out what binary we're debugging
 	if [ $os = "Linux" ]; then 
 	     BINARYNAME=`readlink "/proc/$pid/exe"`
 	elif [ $os = "SunOS" ]; then
@@ -39,7 +50,7 @@ action=mail
 	     exit 1
 	fi
 
-	# Generic header for our email
+	# Generic header for the report
 	echo "The Cherokee 'panic action' script, $0,"
 	echo "was called for pid $pid ($BINARYNAME)."
 	echo
@@ -72,7 +83,7 @@ action=mail
 	echo "Below is a backtrace for this process generated with gdb, which shows"
 	echo "the state of the program at the time the error occured.  You are"
 	echo "encouraged to submit this information as a bug report in the Cherokee"
-	echo "bug traq system:  http://bugs.0x50.org"
+	echo "bug traq system:  http://bugs.cherokee-project.com"
 	echo
 	echo "Operating System: `uname -a`"
 	echo "Debugger: $debugger"
@@ -80,7 +91,8 @@ action=mail
 
 	# Get the backtrace
 	if [ x$debugger = x$gdb ]; then 
-	     tmp_cmd=`mktemp -t` || exit 1
+	     tmp_cmd=`mktemp -t` ||
+	     tmp_cmd=`mktemp "/tmp/chrk.XXXXXX"` || exit 1
 
 		( echo "print cherokee_version"
 		  echo "thread apply all bt full"
@@ -96,13 +108,13 @@ action=mail
 ) | ( 
     case "$action" in
 	   mail)
-		  mail -s "Segfault in Cherokee" root
+		  /usr/sbin/sendmail -t
 		  ;;
 	   cat)
 		  cat -
 		  ;;
 	   *)
-		  echo "ERROR: Wrong action."
+		  echo "ERROR: Wrong action: \"$action\""
 		  exit 1
     esac;
 )
